
<div id="post-add">
    <h1>Add a new post</h1>
    
    <div id="post-types">
        <ul>
            <li><a href="">Standard</a></li>
            <li><a href="">Link</a></li>
        </ul>
    </div>
    
    <div id="post-form-standard" class="pass-form">
        <?php echo $this->standardForm . PHP_EOL; ?>
    </div>
    
    <div id="post-form-link" class="post-form" style="display: none;">
        <?php echo $this->linkForm . PHP_EOL; ?>
    </div>
</div>
